/**
 * Real WebSocket bridge between the web dashboard and the downloadable Windows
 * desktop agent (server/desktopAgentCode.ts). This is the piece that was
 * previously missing entirely: the Python agent tried to connect to
 * `wss://.../ws/agent`, but nothing in server.ts ever listened on that path,
 * so commands generated by /api/chat never reached a real machine.
 *
 * Responsibilities:
 *  - Accept the agent's WebSocket connection at /ws/agent and authenticate it
 *    against the pairing code.
 *  - Track connection state in agentBridge's AgentStatus so the UI reflects
 *    reality instead of a hardcoded "connected: true".
 *  - Forward live telemetry from the agent into agentBridge's metrics store.
 *  - Provide sendCommandToAgent(), a request/response helper that
 *    /api/chat and /api/agent/execute use to actually run a command on the
 *    paired PC and wait for the result.
 */
import type { Server as HTTPServer } from "http";
import crypto from "crypto";
import { WebSocketServer, WebSocket } from "ws";
import { updateAgentStatus, setLiveMetrics, setLiveProcesses } from "./agentBridge.js";

interface PendingRequest {
  resolve: (result: any) => void;
  reject: (err: Error) => void;
  timer: NodeJS.Timeout;
}

// Pairing code the agent must present. No hardcoded fallback: if this isn't
// set, a random one is generated and printed once at startup (see server.ts
// console output), so nobody is ever running with the well-known default
// "JARVIS-8849" that ships in this repo's history.
const EXPECTED_PAIRING_CODE = process.env.JARVIS_PAIRING_CODE || crypto.randomBytes(8).toString("hex");
if (!process.env.JARVIS_PAIRING_CODE) {
  console.warn(`[SECURITY] JARVIS_PAIRING_CODE not set. Generated one for this session: ${EXPECTED_PAIRING_CODE}`);
  console.warn("[SECURITY] Set JARVIS_PAIRING_CODE in .env.local and on the agent to keep it stable.");
}

let agentSocket: WebSocket | null = null;
const pending = new Map<string, PendingRequest>();
let requestCounter = 0;

export function isAgentConnected(): boolean {
  return agentSocket !== null && agentSocket.readyState === WebSocket.OPEN;
}

export function attachAgentWebSocketServer(server: HTTPServer) {
  const wss = new WebSocketServer({ server, path: "/ws/agent" });

  wss.on("connection", (ws) => {
    let authenticated = false;
    console.log("[Agent WS] Incoming connection, awaiting auth handshake...");

    ws.on("message", (raw) => {
      let data: any;
      try {
        data = JSON.parse(raw.toString());
      } catch {
        return; // ignore malformed frames
      }

      if (data.type === "agent_auth") {
        if (data.pairingCode !== EXPECTED_PAIRING_CODE) {
          ws.send(JSON.stringify({ type: "auth_error", message: "Invalid pairing code" }));
          ws.close();
          return;
        }
        authenticated = true;

        // Only one active agent at a time - replace any stale connection.
        if (agentSocket && agentSocket !== ws && agentSocket.readyState === WebSocket.OPEN) {
          try { agentSocket.close(); } catch { /* ignore */ }
        }
        agentSocket = ws;

        updateAgentStatus({
          connected: true,
          paired: true,
          deviceName: data.deviceName || "Windows-PC",
          platform: data.platform || "Unknown",
        });
        console.log(`[Agent WS] Agent authenticated: ${data.deviceName} (${data.platform})`);
        return;
      }

      if (!authenticated) return; // drop anything sent before a valid auth

      if (data.type === "telemetry") {
        setLiveMetrics(data);
        if (Array.isArray(data.processes)) {
          setLiveProcesses(data.processes);
        }
        return;
      }

      if (data.type === "command_result") {
        const req = data.requestId && pending.get(data.requestId);
        if (req) {
          clearTimeout(req.timer);
          pending.delete(data.requestId);
          req.resolve(data);
        }
        return;
      }
    });

    ws.on("close", () => {
      if (ws === agentSocket) {
        agentSocket = null;
        updateAgentStatus({ connected: false });
        console.log("[Agent WS] Agent disconnected.");
      }
    });

    ws.on("error", (err) => {
      console.error("[Agent WS] Socket error:", err.message);
    });
  });

  console.log("[Agent WS] Bridge listening at /ws/agent");
}

/**
 * Sends a structured command to the connected desktop agent and resolves
 * once the agent reports back a command_result for the matching requestId
 * (or rejects on timeout / no agent connected).
 */
export function sendCommandToAgent(
  action: string,
  params: Record<string, any> = {},
  timeoutMs = 12000
): Promise<{ success: boolean; result: string; action: string }> {
  return new Promise((resolve, reject) => {
    if (!isAgentConnected()) {
      reject(new Error("No desktop agent is connected. Download and run the agent, then try again."));
      return;
    }

    const requestId = `req-${Date.now()}-${requestCounter++}`;
    const timer = setTimeout(() => {
      pending.delete(requestId);
      reject(new Error("Desktop agent did not respond in time."));
    }, timeoutMs);

    pending.set(requestId, { resolve, reject, timer });

    agentSocket!.send(JSON.stringify({
      type: "execute_command",
      requestId,
      action,
      params,
    }));
  });
}
